version: 2.1

workflows:
  mainflow:
    jobs:
      - buildit

jobs:
  buildit:
    docker:
      - image: docker:25.0.5-git
    resource_class: small
    steps:
      - run: apk add python3
      - checkout
      - run: python --version
