version: 2.1

workflows:
  mainflow:
    jobs:
      - erunner
      - buildit:
          context:
            - dockerhubaccess

jobs:
  erunner:
    machine: true
    resource_class: imagel/experirun
    steps:
      - run: echo "Hi I'm on Runners!"
      - run:
          name: Check environment
          command: |
            pwd
            ls -lah .
            ls -lah ..
            ls -lah ../..
            ls -lah /
            echo hellothisisrunner > ../runfile

  buildit:
    docker:
      - image: cimg/base:2026.01
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Setup the hub"
          command: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: "Build the image"
          command: |
            cd hellodock
            TAG=build-0.1.$CIRCLE_BUILD_NUM
            docker build -t okriof/imagel:$TAG .
      - run:
          name: "Push the image"
          command: |
            TAG=build-0.1.$CIRCLE_BUILD_NUM
            docker push okriof/imagel:$TAG
