version: 2.1

workflows:
  mainflow:
    jobs:
      - buildit

jobs:
  buildit:
    docker:
      - image: docker:25.0.5-git
    resource_class: small
    steps:
      - run:
          name: "Install the third snake!"
          command: apk add python3
      - checkout
      - run:
          name: "Check the version"
          command: "python --version"
