version: 2.1

workflows:
  mainflow:
    jobs:
      - buildit

jobs:
  buildit:
    docker:
      - image: cimg/base:2026.01
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: "Build the image"
          command: |
            cd hellodock
            TAG=build-0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/imagel:$TAG .
      - run:
          name: "Push the image"
          command: |
            TAG=build-0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/imagel:$TAG
